name = "SourPatch-Modpack"
author = "SourPatch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c6fa7994580b83074c3ec383241d86dba1183dc8d32250176587d4e953bc5ad"

[versions]
minecraft = "1.20.1"
quilt = "0.20.1"
