name = "SourPatch-Modpack"
author = "SourPatch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bfe9e4f3a8a7a97a9900211d70eac129953f8b9623996acb4652a21561c1ca7"

[versions]
minecraft = "1.20.1"
quilt = "0.20.1"
