name = "SourPatch-Modpack"
author = "SourPatch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61eea778ff82fb532cac21e45fc7203cdee6456a0f7b757bd48ce6d49c08a91f"

[versions]
minecraft = "1.20.1"
quilt = "0.20.1"
