name = "SourPatch-Modpack"
author = "SourPatch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6cf437f262070bfd6b189848af9b6e032b8f6f6e578b7f8134c1e45bddf020ce"

[versions]
minecraft = "1.20.1"
quilt = "0.20.1"
