name = "SourPatch-Modpack"
author = "SourPatch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a74f804b2fcf79853ccebf460d94287ea5599e5945bbcddc18eef626a0dba44"

[versions]
minecraft = "1.20.1"
quilt = "0.20.1"

[options]
acceptable-game-versions = []
