name = "SourPatch-Modpack"
author = "SourPatch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a47d0b347fb96743306ca2816dc537490c7dee8fb45d6ad9269f14ade178b0e7"

[versions]
minecraft = "1.20.1"
quilt = "0.20.1"
