name = "SourPatch-Modpack"
author = "SourPatch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "968b03413d5f92b8ddc106f8a7e497e8dbbc4b7771b20a59a939dc0a766dcfe9"

[versions]
minecraft = "1.20.1"
quilt = "0.20.1"
