name = "SourPatch-Modpack"
author = "SourPatch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47e5baea98c351284fda298e14ad354e9cffe114830a74ca8da88cd20c16d632"

[versions]
minecraft = "1.20.1"
quilt = "0.20.1"
